### ISSUE TITLE
RFC: v1 roadmap

### ISSUE THREAD

**Issue by kmjennison** [gladly-team/next-firebase-auth#265]
`next-firebase-auth` has been reasonably stable for a while now and is already used in production apps, so it feels an appropriate time to move toward a v1 release.

This is an in-progress document of the changes that might land in v1. Please comment with any feedback or questions.

The unstable releases are available as `next-firebase-auth@canary`. When contributing, please make pull requests to the **v1.x** branch.

**Demo:** the demo app is deployed [here](https://nfa-example-git-v1x-gladly-team.vercel.app/).

---

### Prerequisites
- [x] Set up a canary/next/v1 branch and release process (@kmjennison)
- [x] Set up a canary live demo (@kmjennison)

### Making the package work better
- [x] #164 
    * Drop support for Firebase <9
- [x] #174 
- [x] Fix bug with HMR: #163 
    * Potentially via #207
- [x] #142 
- [x] #488 

### Making the package more flexible
- [x] ~#190~
  **Deferred:** we'll delay this to a potential later release because 1) we won't want to complicate adoption of Firebase v9, 2) we haven't identified a suitable cookies library, and 3) this library might have a cookie-free future (see #287).
    - [x] Identify a suitable cookies library
    - [x] Identify a clear migration strategy for existing apps to avoid cookie mismatches
    - [x] Implement
    - [x] Write migration documents
- [x] #223
- [x] #233 
- [x] #444

### Preventing incorrect use
- [x] #155 
- [x] #195

### Developer tools
- [x] #389 

### Cleanup
- [x] Make API name changes
  * Instances of AuthUser: `AuthUser` --> `user`
  * `withAuthUser` --> `withUser`
  * `withAuthUserTokenSSR` --> `withUserTokenSSR`
  * `withAuthUserSSR` --> `withUserSSR`
  * `useAuthUser` --> `useUser`
 - [x] Review naming of exported types

### Before release
- [x] #296 
- [x] If needed, provide a codemod (jscodeshift)
- [x] Write migration guide
- [x] Ensure README is up to date

**Comment by HofmannZ** [comment]
Hi, I'm picking up Firebase v9 support 👨‍💻

**Comment by VewMet** [comment]
When will this library be available for next 12 version ?

**Comment by kmjennison** [comment]
@VewMet Next 12 is supported in the latest releases.

**Comment by Patrik-svobodik** [comment]
Firebase-admin 10.0.0 support should also be added to the roadmap

**Comment by kmjennison** [comment]
@Patrik-svobodik Firebase admin v10 is already supported.

**Comment by seanaguinaga** [comment]
Is Next.js' middleware functionality a place that next-firebase-auth could live? I assume it would be more performant? But does that make the hybrid server and client approach currently used almost impossible?

https://nextjs.org/docs/middleware

That could mean that pages lose auth/redirect on a page by page basis, instead be determined by file placement.

**Comment by kmjennison** [comment]
@seanaguinaga Thanks for flagging this. I opened an issue for middleware discussion here: #418

**Comment by DiegoGonzalezCruz** [comment]
Hi guys, hope everything is going great. I am wondering if you have an estimated ETA for v1?

**Comment by kmjennison** [comment]
@DiegoGonzalezCruz We don't have an ETA—we're making progress as we have time. We welcome contributions on open issues. Meanwhile, `next-firebase-auth@canary` is available to use.

**Comment by jodik** [comment]
Hi,

it seems admin side is also modular:
import { initializeApp } from 'firebase-admin/app';


Currently we do:
import * as admin from 'firebase-admin'
admin.initializeApp()

**Comment by raajnadar** [comment]
@kmjennison is that safe to use `next-firebase-auth@canary` for a production app or the canary is for testing?

**Comment by kmjennison** [comment]
@raajnadar Yes, the canary releases are intended to be fully functional and usable in production. However, they'll be less stable and less tested than major releases, so you should only use it if you have tolerance for possible bugs or breaking changes.

The current canary version will see more breaking changes before it hits v1 stable. See [release notes](https://github.com/gladly-team/next-firebase-auth/releases) for these changes.

**Comment by seanaguinaga** [comment]
@kmjennison  I am having a hard time upgrading to v17 - the admin config for initAuth is different?

have a complete example?

**Comment by kmjennison** [comment]
@seanaguinaga The config hasn't changed, but there are some breaking changes in v1.0.0-canary.17 (see [release notes](https://github.com/gladly-team/next-firebase-auth/releases/tag/v1.0.0-canary.17)). Notably, we dropped support for `firebase-admin` v9 and removed the `getFirebaseAdmin` method. Instead, if you need the Firebase admin app, [import it directly](https://github.com/gladly-team/next-firebase-auth/tree/v1.x#using-the-firebase-apps).

**Comment by louisgv** [comment]
@kmjennison I tried `canary.17` and am receiving this error:
```
Error: The default Firebase app does not exist. Make sure you call initializeApp() before using any of the Firebase services.
```
canary.16 worked. With canary17, I removed the getFirebaseAdmin and replaced them with `getFirestore()` directly. I also ran initAuth() before these API route, even placed the initAuth right before the getFirestore() like this:

```
initAuth()
const firestore = getFirestore()
```

And the error still throw

**Comment by louisgv** [comment]
More context: I'm invoking these inside a `getServerSideProps()`

**Comment by louisgv** [comment]
Fixed it by wrapping the getServerSideProps inside the withAuthUser

**Comment by strid408** [comment]
I'm also having issues with the 'app/no-app' error code when trying to access the admin sdk on the server side. Both in API routes and getserversideprops. Strangely enough, it seems to work sometimes. I got it working suddenly, restarted the app, and then the errors came back..

**Comment by kmjennison** [comment]
If you're running into a bug, please try the [example app](https://github.com/gladly-team/next-firebase-auth/tree/v1.x/example) with your own Firebase credentials (if you haven't already) to see if the bug exists there. Then, please open an issue with a minimal example app and instructions to reproduce.

**Comment by kmjennison** [comment]
**v1 beta is out!** 🎉 Check out the [migration guide](https://github.com/gladly-team/next-firebase-auth/blob/v1.x/MIGRATION.md#v1-from-v0x) and let me know if you run into any issues.

**Comment by kmjennison** [comment]
v1.0.0 has been released!
